name: CI
on:
  push:
    branches: [ dev ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          
      - run: yarn install
      
      - run: yarn build
      
      - run: yarn test

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: public
